server:
  port: 15447
spring:
  datasource:
    url: jdbc:sqlite:SPDNetData.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
spd:
  version: 3.3.6
  netVersion: 0.0.1
  motd: 不欢迎  >:^(
